- name: install packages mysql
  yum: name=mysql state=present

- name: install packages mysqld
  yum: name=mysql-community-server state=present
  poll: 30
  async: 600

- name: install module mysql_variables
  yum: name=MySQL-python state=present

- name: copy mysql configuration
  copy: src=etc/my.cnf dest=/etc/my.cnf
  register: mysql_configured

- name: restart mysqld
  service: name=mysqld state=restarted enabled=yes
  when: mysql_configured.changed
